### ISSUE TITLE
Generate compile_commands.json

### ISSUE THREAD

**Issue by daneov** [mxcl/xcodebuild#117]
Is it, or would it be, possible to execute `xcodebuild | xcpretty -r json-compilation-database` somehow?

My use case: to be able to run `oclint` against the resulting `compile_commands.json` in a next step somewhere.

**Comment by daneov** [comment]
Thanks for your timely reply!

I discovered that `xcpretty` is actually deprecated (has been a while for me). Due to this I found an alternative using C flags, which was introduced a while ago, and still seems to work.

https://gist.github.com/T1T4N/f4d63a44476eb5c7046cc561cb8c7f77#xcconfig

My next issue is getting oclint or infer to work with it, but that's a different track. I'll close this 😊

**Comment by mxcl** [comment]
If you find a way we'd happily add the option.
