### ISSUE TITLE
`xcodebuild -list -json` is exceptionally slow

### ISSUE THREAD

**Issue by mxcl** [mxcl/xcodebuild#13]
In our CI builds the list operation takes ~21 seconds, and the build itself takes ~6 seconds (!)

<img width="336" alt="image" src="https://user-images.githubusercontent.com/58962/120929357-c1a38a00-c6b6-11eb-9d00-479ad587a2f9.png">

This is insane, it will be worth investing time to figure out alternatives or optimizations.

**Comment by mxcl** [comment]
Caught it:

https://github.com/mxcl/StreamReader/pull/4/checks?check_run_id=2765489872

```json
{
  "project" : {
    "configurations" : [
      "Debug",
      "Release"
    ],
    "name" : "StreamReader",
    "schemes" : [
      "StreamReader-Package"
    ],
    "targets" : [
      "Path",
      "Path.swiftPackageDescription",
      "StreamReader",
      "StreamReaderPackageDescription"
    ]
  }
}
build session not created after 15 seconds - still waiting
```

fucking lol. What a crap tool `xcodebuild` is.

**Comment by chris-araman** [comment]
Oops. At least it’s not in the middle of the JSON blob?

**Comment by mxcl** [comment]
Oof. Wrong ticket for this discussion and fix

**Comment by chris-araman** [comment]
Was the slow runtime just due to virtualization (expected), or was there something else going on here?

**Comment by mxcl** [comment]
Not fixed. There might be faster ways to get this info.
