### ISSUE TITLE
Select-only Option?

### ISSUE THREAD

**Issue by JosephDuffy** [mxcl/xcodebuild#46]
Where possible I prefer to test without an Xcode project, but the Xcode selection feature of this action isn't usable without also creating an Xcode project and using `xcodebuild` to run the tests.

Given the name of the project I'm not sure if a select-only option would be appropriate for this action?

I have my own action that updates the Xcode version used within actions but would prefer to use only this action. If this would be an acceptable feature I'd be willing to contribute to the project.

**Comment by mxcl** [comment]
K, so to be clear, you are asking for an option that selects an Xcode, but doesn’t run the build? Because honestly I had to read what you had written three times to assume that.

**Comment by mxcl** [comment]
I'm sure a build action of `none` would be ok.
