### ISSUE TITLE
macOS 12 support

### ISSUE THREAD

**Issue by othyn** [mxcl/xcodebuild#77]
Hi, I see there is a cron runner action to try to update this stuff automagically, but not sure if its picked up the macOS 12 image with Xcode 13.3?

The macOS 12 image is listed here:

https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md

**Comment by mxcl** [comment]
CI updated: https://github.com/mxcl/xcodebuild/pull/79

Is that sufficient?

**Comment by othyn** [comment]
Thank you! Should be all good :)
