### ISSUE TITLE
Specify workspace

### ISSUE THREAD

**Issue by nitrag** [mxcl/xcodebuild#78]
I think there needs to be an GH Action input to specify the `workspace file` because this package doesn't find my workspace. I believe I need to build with workspace because I use CocoaPods and I'm getting this error:

```
no such module 'Alamofire'
  
  import Alamofire
         ^
  
  
  ** BUILD FAILED **
  
  
  The following build commands failed:
  	CompileSwift normal x86_64
  	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
  (2 failures)
  exec: xcodebuild -destination id=86BA49D1-96[18](https://github.com/xxxx/xxxx-ios/runs/6098816862?check_suite_focus=true#step:10:18)-4B0F-8A41-1B9741[22](https://github.com/xxxx/xxx-ios/runs/6098816862?check_suite_focus=true#step:10:22)DCBA -scheme myapp -configuration Release -resultBundlePath build.xcresult build
```

Here's my xcodebuild list without and with workspace:

```
#  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list -json
{
  "project" : {
    "configurations" : [
      "Debug",
      "Release"
    ],
    "name" : "myapp",
    "schemes" : [
      "StoreKitTests",
      "myapp"
    ],
    "targets" : [
      "myapp",
      "myappTests",
      "myappUITests"
    ]
  }
}
#  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace myapp.xcworkspace -list -json
{
  "workspace" : {
    "name" : "myapp",
    "schemes" : [
      "Alamofire",
      "Alamofire-SwiftyJSON",
      "AlamofireImage",
      "....
      "myapp",
      "....
    ]
  }
}
```

**Comment by mxcl** [comment]
If there's only one xcworkspace file this is a bug. Either way we probs need a way to specify it for edge cases anyway.

Code is easy to understand, feel free to PR. If you don’t we’ll get around to it eventually I am sure.

**Comment by allisonmoyer** [comment]
Hey @mxcl I'm running into the same issue. I have some changes ready to PR, but I think I need to be added as a collaborator in order to do so - can you add me?

**Comment by mxcl** [comment]
You don’t need to be a collaborator to PR, you can push to your fork and then pull request here after.

**Comment by allisonmoyer** [comment]
Ah thanks @mxcl ! Just opened
