### ISSUE TITLE
Allow specifying Swift version

### ISSUE THREAD

**Issue by mxcl** [mxcl/xcodebuild#8]
To determine Swift versions for Xcode versions we can use:

https://github.com/mxcl/.github/blob/main/.github/workflows/sniff.yml

(Import it here).

Then every day update a JSON file this action can use to determine Xcode version for Swift semantic version.

Then if we cannot get a specific Swift version we can download it like other actions do, this would allow us to support new Swift on macOS quickly and when the image adds the Xcode that provides it, switch to that making the action quicker.

**Comment by mxcl** [comment]
@chris-araman this is released with 1.1.0

**Comment by chris-araman** [comment]
I'll try it out later today. Thanks!
